In [1]:
# ==============================
# 1. IMPORT LIBRARIES
# ==============================
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

# ==============================
# 2. LOAD DATASET (FULL PATH)
# ==============================
path = r"C:\Users\Subhi Jain\Desktop\dsbda-prac_227\datasets\iris.csv"

df = pd.read_csv(path)

print("Dataset Loaded Successfully")
print(df.head())

# ==============================
# 3. SPLIT FEATURES & TARGET
# ==============================
X = df.iloc[:, :-1]   # all columns except last
y = df.iloc[:, -1]    # last column (species)

# ==============================
# 4. TRAIN-TEST SPLIT
# ==============================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# ==============================
# 5. NAIVE BAYES MODEL
# ==============================
model = GaussianNB()
model.fit(X_train, y_train)

# ==============================
# 6. PREDICTION
# ==============================
y_pred = model.predict(X_test)

print("\nPredictions Done")

# ==============================
# 7. CONFUSION MATRIX
# ==============================
cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:")
print(cm)

# ==============================
# 8. TP, FP, FN, TN
# ==============================
FP = cm.sum(axis=0) - np.diag(cm)
FN = cm.sum(axis=1) - np.diag(cm)
TP = np.diag(cm)
TN = cm.sum() - (FP + FN + TP)

print("\nTrue Positives:", TP)
print("False Positives:", FP)
print("False Negatives:", FN)
print("True Negatives:", TN)

# ==============================
# 9. ACCURACY & ERROR RATE
# ==============================
accuracy = accuracy_score(y_test, y_pred)
error_rate = 1 - accuracy

print("\nAccuracy:", accuracy)
print("Error Rate:", error_rate)

# ==============================
# 10. PRECISION & RECALL
# ==============================
precision = precision_score(y_test, y_pred, average='macro')
recall = recall_score(y_test, y_pred, average='macro')

print("\nPrecision:", precision)
print("Recall:", recall)

Dataset Loaded Successfully
   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Predictions Done

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

True Positives: [19 13 13]
False Positives: [0 0 0]
False Negatives: [0 0 0]
True Negatives: [26 32 32]

Accuracy: 1.0
Error Rate: 0.0

Precision: 1.0
Recall: 1.0
