In [1]:
# =========================================================
# DATA ANALYTICS III - NAIVE BAYES CLASSIFICATION (IRIS)
# =========================================================

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

# =========================================================
# 1. LOAD EXISTING IRIS DATASET
# =========================================================

path = r"C:\Users\Subhi Jain\Desktop\dsbda-prac_227\datasets\Iris.csv"
df = pd.read_csv(path)

print("\n================ IRIS DATASET ================\n")
print(df.head())

# detect target column
target_col = df.columns[-1]

# =========================================================
# 2. SPLIT FEATURES AND TARGET
# =========================================================

X = df.drop(target_col, axis=1)
y = df[target_col]

# =========================================================
# 3. TRAIN-TEST SPLIT
# =========================================================

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# =========================================================
# 4. NAIVE BAYES MODEL
# =========================================================

model = GaussianNB()
model.fit(X_train, y_train)

# =========================================================
# 5. PREDICTION
# =========================================================

y_pred = model.predict(X_test)

# =========================================================
# 6. CONFUSION MATRIX
# =========================================================

cm = confusion_matrix(y_test, y_pred)

print("\n================ CONFUSION MATRIX ================\n")
print(cm)

# =========================================================
# 7. TP, FP, FN, TN (MULTICLASS HANDLING)
# =========================================================

TP = np.diag(cm)
FP = cm.sum(axis=0) - TP
FN = cm.sum(axis=1) - TP
TN = cm.sum() - (FP + FN + TP)

print("\n================ TP, FP, FN, TN ================\n")
print("TP:", TP)
print("FP:", FP)
print("FN:", FN)
print("TN:", TN)

# =========================================================
# 8. METRICS
# =========================================================

accuracy = accuracy_score(y_test, y_pred)
error_rate = 1 - accuracy
precision = precision_score(y_test, y_pred, average="macro")
recall = recall_score(y_test, y_pred, average="macro")

print("\n================ PERFORMANCE METRICS ================\n")
print("Accuracy:", accuracy)
print("Error Rate:", error_rate)
print("Precision:", precision)
print("Recall:", recall)


================ IRIS DATASET ================

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

================ CONFUSION MATRIX ================

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

================ TP, FP, FN, TN ================

TP: [19 13 13]
FP: [0 0 0]
FN: [0 0 0]
TN: [26 32 32]

================ PERFORMANCE METRICS ================

Accuracy: 1.0
Error Rate: 0.0
Precision: 1.0
Recall: 1.0
